/**
 * Harness specification for the meta-agent optimizer.
 *
 * Extends `AgentConfig` with the optimization-relevant surface that
 * the meta-agent modifies between benchmark runs: system prompt,
 * model, tools list, and orchestration strategy description.
 *
 * @since 0.2.0
 */
import { Effect } from 'effect';
import * as Option from 'effect/Option';
import * as Schema from 'effect/Schema';

import { BlueprintPatch } from './BlueprintPatch.js';

// =============================================================================
// Keep / Discard Decision
// =============================================================================

/**
 * Decision on whether to keep or discard a harness change after
 * evaluating benchmark results.
 *
 * @since 0.2.0
 */
export const KeepDecision = Schema.Literals(['keep', 'discard']).annotate({
	title: 'KeepDecision',
	description: 'Whether to keep or discard a harness change after evaluation.'
});

export type KeepDecision = typeof KeepDecision.Type;

// =============================================================================
// Failure Diagnosis
// =============================================================================

/**
 * Structured diagnosis of why tasks failed in a benchmark run.
 *
 * @since 0.2.0
 */
export class FailureDiagnosis extends Schema.Class<FailureDiagnosis>(
	'FailureDiagnosis'
)(
	{
		category: Schema.Literals([
			'misunderstanding',
			'missing_capability',
			'weak_information_gathering',
			'bad_execution_strategy',
			'missing_verification',
			'environment_issue',
			'silent_failure'
		]),
		taskNames: Schema.Array(Schema.String),
		description: Schema.String,
		suggestedFix: Schema.String
	},
	{
		description:
			'Structured failure diagnosis with root cause category and suggested fix.'
	}
) {}

// =============================================================================
// Improvement Proposal
// =============================================================================

/**
 * A proposed harness improvement generated by the meta-agent.
 *
 * @since 0.2.0
 */
export class ImprovementProposal extends Schema.Class<ImprovementProposal>(
	'ImprovementProposal'
)(
	{
		description: Schema.String,
		changeType: Schema.Literals([
			'prompt_tuning',
			'new_tool',
			'tool_modification',
			'strategy_change',
			'model_change',
			'orchestration'
		]),
		rationale: Schema.String,
		affectedFiles: Schema.Array(Schema.String)
	},
	{
		description:
			'A proposed harness improvement with type, rationale, and affected files.'
	}
) {}

// =============================================================================
// Evaluation Result
// =============================================================================

/**
 * Evaluation result comparing a new benchmark run against the baseline.
 *
 * @since 0.2.0
 */
export class EvaluationResult extends Schema.Class<EvaluationResult>(
	'EvaluationResult'
)(
	{
		decision: KeepDecision,
		baselinePassed: Schema.String,
		currentPassed: Schema.String,
		reasoning: Schema.String,
		commit: Schema.OptionFromOptionalKey(Schema.String).pipe(
			Schema.withConstructorDefault(Effect.succeed(Option.none()))
		)
	},
	{
		description:
			'Evaluation comparing benchmark results against baseline with keep/discard decision.'
	}
) {}

// =============================================================================
// Optimizer State
// =============================================================================

/**
 * State of the meta-agent optimization loop.
 *
 * @since 0.2.0
 */
export class OptimizerState extends Schema.Class<OptimizerState>(
	'OptimizerState'
)(
	{
		iteration: Schema.Number,
		bestScore: Schema.Number,
		bestPassed: Schema.String,
		consecutiveDiscards: Schema.Number,
		totalKeeps: Schema.Number,
		totalDiscards: Schema.Number
	},
	{
		description: 'Current state of the hill-climbing optimization loop.'
	}
) {}

/**
 * Initial optimizer state with zero progress.
 *
 * @since 0.2.0
 */
export const initialOptimizerState = new OptimizerState({
	iteration: 0,
	bestScore: 0,
	bestPassed: '0/0',
	consecutiveDiscards: 0,
	totalKeeps: 0,
	totalDiscards: 0
});

// =============================================================================
// Harness File
// =============================================================================

/**
 * Contents of an editable harness file, read for the coding agent.
 *
 * @since 0.3.0
 */
export class HarnessFile extends Schema.Class<HarnessFile>('HarnessFile')(
	{
		path: Schema.String,
		content: Schema.String
	},
	{ description: 'Contents of an editable harness file.' }
) {}

// =============================================================================
// Harness Manifest
// =============================================================================

/**
 * Defines the editable vs fixed boundary for the meta-agent optimizer.
 * Equivalent to the `FIXED ADAPTER BOUNDARY` comment in the Python codebase.
 *
 * @since 0.3.0
 */
export class HarnessManifest extends Schema.Class<HarnessManifest>(
	'HarnessManifest'
)(
	{
		editableFiles: Schema.NonEmptyArray(Schema.String),
		fixedFiles: Schema.Array(Schema.String),
		buildCommand: Schema.String,
		benchmarkTasksDir: Schema.String
	},
	{
		description:
			'Defines the editable vs fixed boundary for the meta-agent optimizer.'
	}
) {}

/**
 * Default harness manifest for the effect-autoagent project.
 *
 * @since 0.3.0
 */
export const defaultManifest = new HarnessManifest({
	editableFiles: [
		'src/AgentConfig.ts',
		'src/AgentToolkit.ts',
		'src/AgentExecutor.ts'
	],
	fixedFiles: [
		'src/Atif.ts',
		'src/Metrics.ts',
		'src/TrajectoryConverter.ts',
		'src/EffectAiConverter.ts',
		'src/ExperimentLog.ts',
		'src/BenchmarkRunner.ts',
		'src/ContainerManager.ts',
		'src/Environment.ts',
		'src/Errors.ts'
	],
	buildCommand: 'bun run check',
	benchmarkTasksDir: 'tasks'
});

// =============================================================================
// Diagnosis Output (for meta-agent generateObject)
// =============================================================================

/**
 * Structured output from the meta-agent diagnosis phase.
 *
 * @since 0.3.0
 */
export class DiagnosisOutput extends Schema.Class<DiagnosisOutput>(
	'DiagnosisOutput'
)(
	{
		diagnoses: Schema.Array(FailureDiagnosis),
		proposal: ImprovementProposal
	},
	{
		description: 'Structured output from the meta-agent diagnosis phase.'
	}
) {}

// =============================================================================
// Blueprint-Aware Improvement Proposal
// =============================================================================

/**
 * A proposed improvement expressed as blueprint patches.
 *
 * @since 0.3.0
 */
export class BlueprintProposal extends Schema.Class<BlueprintProposal>(
	'BlueprintProposal'
)(
	{
		description: Schema.String,
		rationale: Schema.String,
		patches: Schema.Array(BlueprintPatch)
	},
	{ description: 'A proposed improvement expressed as blueprint patches.' }
) {}

/**
 * Structured output from blueprint-aware diagnosis.
 *
 * @since 0.3.0
 */
export class BlueprintDiagnosisOutput extends Schema.Class<BlueprintDiagnosisOutput>(
	'BlueprintDiagnosisOutput'
)(
	{
		diagnoses: Schema.Array(FailureDiagnosis),
		proposal: BlueprintProposal
	},
	{
		description:
			'Structured output from blueprint-aware meta-agent diagnosis.'
	}
) {}
